In [8]:
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [9]:
a.dtype

dtype('int32')

In [11]:
a.astype("int64")

array([1, 2, 3, 4, 5], dtype=int64)

In [13]:
a.min()

1

In [14]:
a.max()

5

In [15]:
a.sum()

15

In [16]:
a.mean()

3.0

In [17]:
a.var()

2.0

In [18]:
a.std()

1.4142135623730951

In [19]:
a.argmax()

4

In [20]:
a.argmin()

0

In [22]:
s=np.random.randint(1,10,(4,3))
print(s)

[[5 6 9]
 [5 8 7]
 [6 9 2]
 [6 9 1]]


In [23]:
zip(s)

In [24]:
enumerate(s)