In [1]:
import numpy as np

In [ ]:
#task

In [30]:
np.linspace(2,4,num=5)

array([2. , 2.5, 3. , 3.5, 4. ])

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [ ]:
#task 2

In [9]:
b=np.ones((4,5),dtype=np.int64)
print(b)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
#task3

In [10]:
d=np.arange(0,20)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [29]:
x = np.arange(20).reshape((4,5))

print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
