In [8]:
import numpy as np
a= np.array([1,2,3,6,7])
print(a)

[1 2 3 6 7]


In [9]:
b = np.array([1, 2, 3, 4, 5])

print(b)

[1 2 3 4 5]


In [11]:
np.add(a,b)

array([ 2,  4,  6, 10, 12])

In [12]:
np.multiply(a,b)

array([ 1,  4,  9, 24, 35])

In [13]:
np.divide(a,b)

array([1. , 1. , 1. , 1.5, 1.4])

In [14]:
np.dot(a,b)

73